# path : /apps/android/gradle.properties
# THIS IS ONLY DEMO 
# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# Kotlin code style for this project: "official" or "obsolete"
kotlin.code.style=official

# Gradle performance settings
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.vfs.watch=true

# Kotlin performance settings
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.compiler.execution.strategy=in-process

# Android build settings
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# ----- MUST FILL THESE IN YOUR FINAL BUILD ----
# Release signing config
HELLO_UPLOAD_STORE_FILE= SECRETS.jts file here
HELLO_UPLOAD_KEY_ALIAS= name here
HELLO_UPLOAD_STORE_PASSWORD=PASS HERE
HELLO_UPLOAD_KEY_PASSWORD=PASS HERE